/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddHwPanel: typeof import('./src/components/AddHwPanel.vue')['default']
    Bg_Normal: typeof import('./src/components/Bg_Normal.vue')['default']
    Bg_StarrySky: typeof import('./src/components/Bg_StarrySky.vue')['default']
    Bg_StarrySkySass: typeof import('./src/components/Bg_StarrySkySass.vue')['default']
    CourseScheduleItemPanel: typeof import('./src/components/CourseScheduleItemPanel.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElCountdown: typeof import('element-plus/es')['ElCountdown']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Hwcontent: typeof import('./src/components/Hwcontent.vue')['default']
    HwDialog: typeof import('./src/components/HwDialog.vue')['default']
    HwStucontent: typeof import('./src/components/HwStucontent.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PdfPreview: typeof import('./src/components/PdfPreview.vue')['default']
    PublicHwPanel: typeof import('./src/components/PublicHwPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Submenu: typeof import('./src/components/Submenu.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
  }
}
